import type { NarrativeStep } from './NarrativeEngine'

// Act 1: Enter World - user walks from road to plaza
export const ACT_1_ENTER: NarrativeStep[] = [
  { type: 'callback', params: { action: 'start_daily_behavior' } },
  { type: 'camera_move', params: { target: { x: 20, z: 23 } }, durationMs: 500 },
  { type: 'npc_move', params: { id: 'user', target: { x: 20, z: 18 }, speed: 2.5 } },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'npc_move', params: { id: 'user', target: { x: 17, z: 18 }, speed: 2.5 } },
  { type: 'camera_move', params: { target: { x: 17, z: 17 }, follow: 'user' } },
]

// Act 2: Producer Greeting
export const ACT_2_GREETING: NarrativeStep[] = [
  { type: 'callback', params: { action: 'stop_daily_behavior' } },
  { type: 'npc_move', params: { id: 'producer', target: { x: 17, z: 15.8 }, speed: 3 } },
  { type: 'wait', params: {}, durationMs: 300 },
  { type: 'npc_state', params: { id: 'producer', action: 'lookAt', target: { x: 17, z: 18 } } },
  { type: 'npc_state', params: { id: 'user', action: 'lookAt', target: { x: 17, z: 15.8 } } },
  { type: 'dialog', params: { from: 'Producer', text: '嗨！欢迎来到小镇！我是这里的制作人。告诉我你想做什么吧！' }, durationMs: 3000 },
  { type: 'callback', params: { action: 'enable_input' } },
]

// Act 3: User requests game (triggered by user message)
export const ACT_3_REQUEST: NarrativeStep[] = [
  { type: 'dialog', params: { from: 'Producer', text: '好主意！让我召唤团队来帮你！' }, durationMs: 2500 },
  { type: 'wait', params: {}, durationMs: 500 },
]

// Act 4: Summon team (planner + explorer + coder + architect)
export const ACT_4_SUMMON: NarrativeStep[] = [
  { type: 'npc_state', params: { id: 'producer', action: 'lookAt', target: { x: 17, z: 17.5 } } },
  { type: 'fx', params: { effect: 'summon_ripple', position: { x: 17, z: 17 } } },
  { type: 'wait', params: {}, durationMs: 350 },
  { type: 'fx', params: { effect: 'summon_ripple', position: { x: 17, z: 17 } } },
  { type: 'wait', params: {}, durationMs: 350 },
  { type: 'fx', params: { effect: 'summon_ripple', position: { x: 17, z: 17 } } },
  { type: 'wait', params: {}, durationMs: 350 },
  { type: 'fx', params: { effect: 'summon_ripple', position: { x: 17, z: 17 } } },
  { type: 'wait', params: {}, durationMs: 350 },
  { type: 'fx', params: { effect: 'summon_ripple', position: { x: 17, z: 17 } } },
  { type: 'wait', params: {}, durationMs: 400 },
  { type: 'parallel', params: { steps: [
    { type: 'camera_move', params: { target: { x: 29, z: 12 } }, durationMs: 600 },
    { type: 'fx', params: { effect: 'exclamation', npcId: 'planner' } },
    { type: 'npc_anim', params: { id: 'planner', anim: 'wave' } },
  ] } },
  { type: 'wait', params: {}, durationMs: 800 },
  { type: 'parallel', params: { steps: [
    { type: 'camera_move', params: { target: { x: 6, z: 7 } }, durationMs: 600 },
    { type: 'fx', params: { effect: 'exclamation', npcId: 'explorer' } },
    { type: 'npc_anim', params: { id: 'explorer', anim: 'wave' } },
  ] } },
  { type: 'wait', params: {}, durationMs: 800 },
  { type: 'parallel', params: { steps: [
    { type: 'camera_move', params: { target: { x: 6, z: 12 } }, durationMs: 600 },
    { type: 'fx', params: { effect: 'exclamation', npcId: 'coder' } },
    { type: 'npc_anim', params: { id: 'coder', anim: 'wave' } },
  ] } },
  { type: 'wait', params: {}, durationMs: 800 },
  { type: 'parallel', params: { steps: [
    { type: 'camera_move', params: { target: { x: 6, z: 17 } }, durationMs: 600 },
    { type: 'fx', params: { effect: 'exclamation', npcId: 'architect' } },
    { type: 'npc_anim', params: { id: 'architect', anim: 'wave' } },
  ] } },
  { type: 'wait', params: {}, durationMs: 800 },
  { type: 'camera_move', params: { target: { x: 17, z: 17 } }, durationMs: 800 },
  { type: 'progress', params: { current: 0, total: 4, label: '团队集结中...' } },
  { type: 'parallel', params: { steps: [
    { type: 'npc_move', params: { id: 'planner', target: { x: 14, z: 17.5 }, speed: 5 } },
    { type: 'npc_move', params: { id: 'explorer', target: { x: 16, z: 17.5 }, speed: 5 } },
    { type: 'npc_move', params: { id: 'coder', target: { x: 18, z: 17.5 }, speed: 5 } },
    { type: 'npc_move', params: { id: 'architect', target: { x: 20, z: 17.5 }, speed: 5 } },
  ] } },
  { type: 'progress', params: { current: 4, total: 4, label: '团队就绪！' } },
  { type: 'npc_state', params: { id: 'planner', action: 'lookAt', target: { x: 17, z: 15.8 } } },
  { type: 'npc_state', params: { id: 'explorer', action: 'lookAt', target: { x: 17, z: 15.8 } } },
  { type: 'npc_state', params: { id: 'coder', action: 'lookAt', target: { x: 17, z: 15.8 } } },
  { type: 'npc_state', params: { id: 'architect', action: 'lookAt', target: { x: 17, z: 15.8 } } },
  { type: 'npc_state', params: { id: 'user', action: 'lookAt', target: { x: 17, z: 15.8 } } },
  { type: 'npc_anim', params: { id: 'planner', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'architect', anim: 'idle' } },
  { type: 'wait', params: {}, durationMs: 1000 },
  { type: 'progress', params: { current: 0, total: 0 } },
]

// Act 5: Assign tasks (planner → art → dev A → dev B)
export const ACT_5_ASSIGN: NarrativeStep[] = [
  { type: 'npc_state', params: { id: 'producer', action: 'lookAt', target: { x: 14, z: 17.5 } } },
  { type: 'dialog', params: { from: 'Producer', text: '小策，你先输出游戏策划案，给大家明确方向！' }, durationMs: 2500 },
  { type: 'npc_state', params: { id: 'planner', action: 'nod' } },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'npc_state', params: { id: 'producer', action: 'lookAt', target: { x: 16, z: 17.5 } } },
  { type: 'dialog', params: { from: 'Producer', text: '小画，等策划案出来后，你负责场景美术和角色设计！' }, durationMs: 2500 },
  { type: 'npc_state', params: { id: 'explorer', action: 'nod' } },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'npc_state', params: { id: 'producer', action: 'lookAt', target: { x: 18, z: 17.5 } } },
  { type: 'dialog', params: { from: 'Producer', text: '阿码，你来实现核心战斗和交互系统！' }, durationMs: 2500 },
  { type: 'npc_state', params: { id: 'coder', action: 'nod' } },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'npc_state', params: { id: 'producer', action: 'lookAt', target: { x: 20, z: 17.5 } } },
  { type: 'dialog', params: { from: 'Producer', text: '阿构，你负责地图生成和关卡系统！' }, durationMs: 2500 },
  { type: 'npc_state', params: { id: 'architect', action: 'nod' } },
  { type: 'wait', params: {}, durationMs: 800 },
]

// Act 6: Walk to office
export const ACT_6_TO_OFFICE: NarrativeStep[] = [
  { type: 'dialog', params: { from: 'Producer', text: '走，去办公室开工！' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'npc_move', params: { id: 'producer', target: { x: 17, z: 3 }, speed: 3 } },
  { type: 'camera_move', params: { target: { x: 17, z: 3 }, follow: 'producer' } },
  { type: 'parallel', params: { steps: [
    { type: 'npc_move', params: { id: 'planner', target: { x: 14, z: 4 }, speed: 3 } },
    { type: 'npc_move', params: { id: 'explorer', target: { x: 16, z: 4 }, speed: 3 } },
    { type: 'npc_move', params: { id: 'coder', target: { x: 18, z: 4 }, speed: 3 } },
    { type: 'npc_move', params: { id: 'architect', target: { x: 20, z: 4 }, speed: 3 } },
    { type: 'npc_move', params: { id: 'user', target: { x: 17, z: 5 }, speed: 2.5 } },
  ] } },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'scene_switch', params: { scene: 'office' } },
]

// Act 7: Office work — 5-stage game dev pipeline
// Workstations: planner=B(10,9), explorer(art)=C(15,9), coder(devA)=F(10,17), architect(devB)=G(15,17)
export const ACT_7_WORK: NarrativeStep[] = [
  { type: 'callback', params: { action: 'setup_office_npcs' } },
  { type: 'wait', params: {}, durationMs: 1500 },

  // ── Stage 1: 策划先行 ──
  { type: 'npc_glow', params: { id: 'planner', color: 'cyan' } },
  { type: 'npc_anim', params: { id: 'planner', anim: 'typing' } },
  { type: 'npc_emoji', params: { id: 'planner', emoji: '📝' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'B', state: 'coding' } },
  { type: 'dialog', params: { from: 'planner', text: '开始撰写游戏策划案...' }, durationMs: 2000 },
  { type: 'npc_glow', params: { id: 'explorer', color: 'yellow' } },
  { type: 'npc_glow', params: { id: 'coder', color: 'yellow' } },
  { type: 'npc_glow', params: { id: 'architect', color: 'yellow' } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: '⏳' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '⏳' } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: '⏳' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'C', state: 'waiting' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'F', state: 'waiting' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'G', state: 'waiting' } },
  { type: 'progress', params: { current: 0, total: 5 } },
  { type: 'wait', params: {}, durationMs: 5000 },
  { type: 'npc_anim', params: { id: 'planner', anim: 'idle' } },
  { type: 'npc_glow', params: { id: 'planner', color: 'green' } },
  { type: 'npc_emoji', params: { id: 'planner', emoji: '✅' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'B', state: 'done' } },
  { type: 'fx', params: { effect: 'completion_stars', npcId: 'planner' } },
  { type: 'dialog', params: { from: 'planner', text: '策划案完成！核心玩法：Roguelike + 实时战斗 ✅' }, durationMs: 2500 },
  { type: 'progress', params: { current: 1, total: 5 } },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'dialog', params: { from: 'Producer', text: '策划案收到，大家按方案开工！' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 500 },

  // ── Stage 2: 美术 + 双开发并行启动 ──
  { type: 'npc_glow', params: { id: 'explorer', color: 'cyan' } },
  { type: 'npc_glow', params: { id: 'coder', color: 'cyan' } },
  { type: 'npc_glow', params: { id: 'architect', color: 'cyan' } },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'typing' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'typing' } },
  { type: 'npc_anim', params: { id: 'architect', anim: 'typing' } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: '🎨' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '⚔️' } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: '🗺️' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'C', state: 'coding' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'F', state: 'coding' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'G', state: 'coding' } },
  { type: 'dialog', params: { from: 'explorer', text: '开始绘制场景概念图和角色立绘...' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 800 },
  { type: 'dialog', params: { from: 'coder', text: '开始实现战斗系统...' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 800 },
  { type: 'dialog', params: { from: 'architect', text: '开始搭建地图生成框架...' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 4000 },

  // ── Stage 3: 中途事件 ──
  { type: 'npc_glow', params: { id: 'coder', color: 'red' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '❌' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'idle' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'F', state: 'error' } },
  { type: 'fx', params: { effect: 'error_sparks', npcId: 'coder' } },
  { type: 'dialog', params: { from: 'coder', text: '啊...combat.ts 类型报错了 ❌' }, durationMs: 2500 },
  { type: 'wait', params: {}, durationMs: 2000 },
  { type: 'npc_glow', params: { id: 'coder', color: 'cyan' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '🔧' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'typing' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'F', state: 'coding' } },
  { type: 'dialog', params: { from: 'coder', text: '找到问题了，接口类型没对齐，继续...' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 1500 },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'idle' } },
  { type: 'npc_glow', params: { id: 'explorer', color: 'green' } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: '✅' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'C', state: 'done' } },
  { type: 'fx', params: { effect: 'completion_stars', npcId: 'explorer' } },
  { type: 'dialog', params: { from: 'explorer', text: '角色立绘和场景美术完成！✅' }, durationMs: 2000 },
  { type: 'progress', params: { current: 2, total: 5 } },
  { type: 'wait', params: {}, durationMs: 800 },

  // ── Stage 4: 美术资产替换集成 ──
  { type: 'dialog', params: { from: 'Producer', text: '美术资产到了，阿构集成一下！' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 500 },
  { type: 'npc_glow', params: { id: 'architect', color: 'cyan' } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: '🔗' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'G', state: 'coding' } },
  { type: 'dialog', params: { from: 'architect', text: '收到，开始替换美术资产...' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 3000 },
  { type: 'npc_anim', params: { id: 'architect', anim: 'idle' } },
  { type: 'npc_glow', params: { id: 'architect', color: 'green' } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: '✅' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'G', state: 'done' } },
  { type: 'fx', params: { effect: 'completion_stars', npcId: 'architect' } },
  { type: 'dialog', params: { from: 'architect', text: '美术资产替换完成，地图生成系统也搞定了！✅' }, durationMs: 2500 },
  { type: 'progress', params: { current: 3, total: 5 } },
  { type: 'wait', params: {}, durationMs: 2000 },
  { type: 'npc_anim', params: { id: 'coder', anim: 'idle' } },
  { type: 'npc_glow', params: { id: 'coder', color: 'green' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '✅' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'F', state: 'done' } },
  { type: 'fx', params: { effect: 'completion_stars', npcId: 'coder' } },
  { type: 'dialog', params: { from: 'coder', text: '战斗和交互系统完成！✅' }, durationMs: 2000 },
  { type: 'progress', params: { current: 4, total: 5 } },
  { type: 'wait', params: {}, durationMs: 1000 },

  // ── Stage 5: 策划验收 ──
  { type: 'npc_glow', params: { id: 'planner', color: 'cyan' } },
  { type: 'npc_anim', params: { id: 'planner', anim: 'typing' } },
  { type: 'npc_emoji', params: { id: 'planner', emoji: '🔍' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'B', state: 'coding' } },
  { type: 'dialog', params: { from: 'planner', text: '我来验一下核心流程...' }, durationMs: 2000 },
  { type: 'wait', params: {}, durationMs: 2000 },
  { type: 'npc_anim', params: { id: 'planner', anim: 'idle' } },
  { type: 'npc_glow', params: { id: 'planner', color: 'green' } },
  { type: 'npc_emoji', params: { id: 'planner', emoji: '✅' } },
  { type: 'callback', params: { action: 'screen_state', workstation: 'B', state: 'done' } },
  { type: 'fx', params: { effect: 'completion_stars', npcId: 'planner' } },
  { type: 'dialog', params: { from: 'planner', text: '玩法流程验证通过！✅' }, durationMs: 2000 },
  { type: 'progress', params: { current: 5, total: 5, label: '█████ 5/5 ✓' } },
  { type: 'wait', params: {}, durationMs: 1000 },

  // ── 全员欢呼 ──
  { type: 'npc_anim', params: { id: 'planner', anim: 'cheer' } },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'cheer' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'cheer' } },
  { type: 'npc_anim', params: { id: 'architect', anim: 'cheer' } },
  { type: 'npc_emoji', params: { id: 'planner', emoji: '🎉' } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: '🎉' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '🎉' } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: '🎉' } },
  { type: 'wait', params: {}, durationMs: 2000 },
  { type: 'npc_emoji', params: { id: 'planner', emoji: null } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: null } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: null } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: null } },
  { type: 'npc_anim', params: { id: 'planner', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'architect', anim: 'idle' } },

  { type: 'dialog', params: { from: 'Producer', text: '全部完成了！游戏已经打包好了！' }, durationMs: 3000 },
  { type: 'wait', params: {}, durationMs: 1000 },
]

// Act 8: Publish — show game result in office
export const ACT_8_PUBLISH: NarrativeStep[] = [
  { type: 'callback', params: { action: 'show_game_publish' } },
  { type: 'wait', params: {}, durationMs: 2000 },
  { type: 'npc_anim', params: { id: 'planner', anim: 'cheer' } },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'cheer' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'cheer' } },
  { type: 'npc_anim', params: { id: 'architect', anim: 'cheer' } },
  { type: 'npc_emoji', params: { id: 'planner', emoji: '🎉' } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: '🎉' } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: '🎉' } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: '🎉' } },
  { type: 'dialog', params: { from: 'Producer', text: '这是你的第一个作品！来试玩一下吧！🎉' }, durationMs: 4000 },
  { type: 'wait', params: {}, durationMs: 4000 },
  { type: 'npc_emoji', params: { id: 'planner', emoji: null } },
  { type: 'npc_emoji', params: { id: 'explorer', emoji: null } },
  { type: 'npc_emoji', params: { id: 'coder', emoji: null } },
  { type: 'npc_emoji', params: { id: 'architect', emoji: null } },
  { type: 'npc_anim', params: { id: 'planner', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'explorer', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'coder', anim: 'idle' } },
  { type: 'npc_anim', params: { id: 'architect', anim: 'idle' } },
  { type: 'progress', params: { current: 0, total: 0 } },
]
