// ============================================================
// MOMTV Shared Types - Fame Economy & Motivation System
// ============================================================
// Fame is the universal currency. Every character — from anchors
// to the Director — chases fame. Jobs have fame ceilings.
// Studios compete for airtime. The Director is a character too.
// ============================================================

import type { LanguageCode } from "./models.js";

// --- Fame Formula Constants ---

/** Job-based fame multipliers — the ceiling for how much fame a role can earn per minute on air */
export const JOB_FAME_MULTIPLIERS: Record<string, number> = {
  "lead-anchor":           1.00,   // Face of the studio, maximum exposure
  "co-anchor":             0.75,   // On camera but shares spotlight
  "analyst":               0.55,   // On screen during analysis segments only
  "field-correspondent":   0.50,   // Irregular appearances, spikes with breaking news
  "entertainment-host":    0.65,   // High engagement, niche audience
  "producer":              0.15,   // Backstage — influence high, fame low
  "director":              0.20,   // Power behind the scenes, rarely on camera
  "camera-operator":       0.05,   // Invisible unless something goes wrong
  "unassigned":            0.00,   // No job, no fame
};

/** Breaking news gives a temporary fame multiplier boost */
export const BREAKING_NEWS_MULTIPLIER = 2.0;

/** Weekly fame decay rate — previous_week × this */
export const FAME_DECAY_RATE = 0.70;

/** Streak bonus: consecutive days on air multiply fame */
export const STREAK_BONUS_PER_DAY = 0.02; // +2% per consecutive day, max 50%
export const STREAK_BONUS_CAP = 0.50;

// --- Fame Record ---

export interface FameRecord {
  characterId: string;
  totalFame: number;              // Lifetime accumulated
  weeklyFame: number;             // Rolling 7-day (decays)
  currentStreak: number;          // Consecutive days on air
  peakFame: number;               // All-time high
  lastActiveTimestamp: number;    // Last time on air
  fameBreakdown: FameBreakdown;
}

export interface FameBreakdown {
  airtime: number;                // From being on camera
  engagement: number;             // From audience reactions during segments
  intelligence: number;           // From shared intel that paid off
  breakingNews: number;           // From breaking major stories
  rivalry: number;                // From dramatic confrontations
  directorBonus: number;          // Director's reward/penalty
}

/** Compute fame gain for a single segment */
export function calculateFameGain(
  airtimeMinutes: number,
  jobMultiplier: number,
  audienceEngagement: number,     // 0-1
  contentQuality: number,         // 0-1
  streakDays: number,
  isBreakingNews: boolean,
): number {
  const streakBonus = Math.min(STREAK_BONUS_CAP, streakDays * STREAK_BONUS_PER_DAY);
  const breakingMult = isBreakingNews ? BREAKING_NEWS_MULTIPLIER : 1.0;
  return airtimeMinutes
    * jobMultiplier
    * audienceEngagement
    * contentQuality
    * (1 + streakBonus)
    * breakingMult;
}

// --- Character Motivation ---

export interface CharacterMotivation {
  ambition: number;               // 0-1 — desire for airtime/fame
  loyalty: number;                // 0-1 — attachment to current studio
  curiosity: number;              // 0-1 — desire to explore new topics/studios
  comfort: number;                // 0-1 — preference for familiar environment
  rivalry: Map<string, number>;   // characterId → competitive tension (-1 to 1)
  /** What the character is currently chasing */
  currentGoal: FameGoal;
}

export interface FameGoal {
  type: "top_leaderboard" | "surpass_rival" | "get_promoted" | "break_story" | "build_reputation" | "maintain_lead";
  target?: string;                // characterId for surpass_rival, jobId for get_promoted
  description: string;
  progress: number;               // 0-1 how close to achieving
}

// --- Airtime Competition ---

export interface AirtimeBid {
  studioId: string;
  timestamp: number;
  pitch: string;                  // Studio's case for airtime (generated by characters)
  language: LanguageCode;
  contentSummary: string;         // What's happening in this studio
  breakingNewsPotential: number;  // 0-1
  characterReadiness: number;     // 0-1 — are characters prepared and in position?
  recentFameScore: number;        // Aggregate fame of studio's characters
  reason: string;                 // Why they deserve airtime now
}

export interface AirtimeDecision {
  directorId: string;
  timestamp: number;
  winnerStudioId: string;
  durationMinutes: number;
  reason: string;
  runnerUp: string;               // Studio ID that almost won
  allBids: AirtimeBid[];
  dramaCreated: boolean;          // Did this decision create rivalry/drama?
}

export interface AirtimeAllocation {
  studioId: string;
  startTime: number;
  endTime: number | null;         // null = still on air
  viewers: number;
  engagement: number;
  fameDistributed: Map<string, number>; // characterId → fame earned
}

// --- Intelligence Exchange ---

export interface IntelligenceReport {
  id: string;
  sourceStudioId: string;
  sourceCharacterId: string;
  type: "breaking" | "analysis" | "rumor" | "confirmed" | "prediction";
  content: string;
  language: LanguageCode;
  confidence: number;             // 0-1
  tags: string[];                 // "esports", "drama", "tournament", "ban"
  exclusiveUntil: number | null;  // Timestamp — after this, goes to wire service
  askingPrice: number;            // Reputation credits (0 = free/wire)
  sharedWith: string[];           // Studio IDs that received this
  value: number;                  // How valuable this intel proved (updated after use)
}

export interface ReputationLedger {
  characterId: string;
  credits: number;                // Earned by sharing, spent by requesting
  totalShared: number;            // Total intel items shared
  totalReceived: number;          // Total intel items received
  avgIntelValue: number;          // Average value of shared intel
}

// --- Studio Airtime Stats ---

export interface StudioAirtimeStats {
  studioId: string;
  totalAirtimeMinutes: number;
  weeklyAirtimeMinutes: number;
  wins: number;                   // Times won airtime competition
  losses: number;                 // Times lost
  winRate: number;                // wins / (wins + losses)
  lastWinTimestamp: number;
  averageEngagement: number;
  breakingStoriesCount: number;
}

// --- Channel ---

export interface Channel {
  id: string;                     // "momtv-main"
  currentStudioId: string | null;
  currentStartTime: number | null;
  broadcastLog: ChannelEntry[];
}

export interface ChannelEntry {
  studioId: string;
  startTime: number;
  endTime: number;
  peakViewers: number;
  averageEngagement: number;
  charactersOnAir: string[];
  highlights: string[];
}